// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package status

import (
	"goframeP/frame/api/status"
)

type ControllerV1 struct{}

func NewV1() status.IStatusV1 {
	return &ControllerV1{}
}
