// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package train

import (
	"goframeP/frame/api/train"
)

type ControllerV1 struct{}

func NewV1() train.ITrainV1 {
	return &ControllerV1{}
}
