// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframeP/frame/internal/dao/internal"
)

// orderDao is the data access object for the frame order.
// You can define custom methods on it to extend its functionality as needed.
type orderDao struct {
	*internal.OrderDao
}

//var (
//	// Order is a globally accessible object for frame order operations.
//	Order = orderDao{internal.NewOrderDao(withTenantFilter())}
//)

//// withTenantFilter 创建租户（渠道）过滤钩子
//// 根据当前登录用户的租户ID自动过滤数据
//func withTenantFilter() gdb.ModelHandler {
//	return func(ctx context.Context, model *gdb.Model) *gdb.Model {
//		// 从 context 中获取租户ID（渠道ID）
//		if tenantId, ok := daoContext.GetTenant(ctx); ok && tenantId > 0 {
//			// 自动添加租户过滤条件
//			// 假设订单表中有 tenant_id 字段
//			return model.Where("tenant_id", tenantId)
//		}
//		return model
//	}
//}

// Add your custom methods and functionality below.
