// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframeP/frame/internal/dao/internal"
)

// partnerCityConfigDao is the data access object for the frame partner_city_config.
// You can define custom methods on it to extend its functionality as needed.
type partnerCityConfigDao struct {
	*internal.PartnerCityConfigDao
}

var (
	// PartnerCityConfig is a globally accessible object for frame partner_city_config operations.
	PartnerCityConfig = partnerCityConfigDao{internal.NewPartnerCityConfigDao()}
)

// Add your custom methods and functionality below.
