// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframeP/frame/internal/dao/internal"
)

// partnerRelationshipDao is the data access object for the frame partner_relationship.
// You can define custom methods on it to extend its functionality as needed.
type partnerRelationshipDao struct {
	*internal.PartnerRelationshipDao
}

var (
	// PartnerRelationship is a globally accessible object for frame partner_relationship operations.
	PartnerRelationship = partnerRelationshipDao{internal.NewPartnerRelationshipDao()}
)

// Add your custom methods and functionality below.
