// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframeP/frame/internal/dao/internal"
)

// priceRulesDao is the data access object for the table price_rules.
// You can define custom methods on it to extend its functionality as needed.
type priceRulesDao struct {
	*internal.PriceRulesDao
}

var (
	// PriceRules is a globally accessible object for table price_rules operations.
	PriceRules = priceRulesDao{internal.NewPriceRulesDao()}
)

// Add your custom methods and functionality below.
