// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframeP/frame/internal/dao/internal"
)

// raiseHandDao is the data access object for the frame raise_hand.
// You can define custom methods on it to extend its functionality as needed.
type raiseHandDao struct {
	*internal.RaiseHandDao
}

var (
	// RaiseHand is a globally accessible object for frame raise_hand operations.
	RaiseHand = raiseHandDao{internal.NewRaiseHandDao()}
)

// Add your custom methods and functionality below.
