// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframeP/frame/internal/dao/internal"
)

// raiseHandDateDao is the data access object for the frame raise_hand_date.
// You can define custom methods on it to extend its functionality as needed.
type raiseHandDateDao struct {
	*internal.RaiseHandDateDao
}

var (
	// RaiseHandDate is a globally accessible object for frame raise_hand_date operations.
	RaiseHandDate = raiseHandDateDao{internal.NewRaiseHandDateDao()}
)

// Add your custom methods and functionality below.
