// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframeP/frame/internal/dao/internal"
)

// raiseHandTimeDao is the data access object for the frame raise_hand_time.
// You can define custom methods on it to extend its functionality as needed.
type raiseHandTimeDao struct {
	*internal.RaiseHandTimeDao
}

var (
	// RaiseHandTime is a globally accessible object for frame raise_hand_time operations.
	RaiseHandTime = raiseHandTimeDao{internal.NewRaiseHandTimeDao()}
)

// Add your custom methods and functionality below.
