// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframeP/frame/internal/dao/internal"
)

// seatTypesDao is the data access object for the table seat_types.
// You can define custom methods on it to extend its functionality as needed.
type seatTypesDao struct {
	*internal.SeatTypesDao
}

var (
	// SeatTypes is a globally accessible object for table seat_types operations.
	SeatTypes = seatTypesDao{internal.NewSeatTypesDao()}
)

// Add your custom methods and functionality below.
