// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframeP/frame/internal/dao/internal"
)

// stationsDao is the data access object for the table stations.
// You can define custom methods on it to extend its functionality as needed.
type stationsDao struct {
	*internal.StationsDao
}

var (
	// Stations is a globally accessible object for table stations operations.
	Stations = stationsDao{internal.NewStationsDao()}
)

// Add your custom methods and functionality below.
