// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"goframeP/frame/internal/dao/internal"
	"goframeP/frame/internal/model"
	"goframeP/frame/internal/model/entity"
)

// tagStatusDao is the data access object for the table tag_status.
// You can define custom methods on it to extend its functionality as needed.
type tagStatusDao struct {
	*internal.TagStatusDao
}

var (
	// TagStatus is a globally accessible object for table tag_status operations.
	TagStatus = tagStatusDao{internal.NewTagStatusDao()}
)

// Add your custom methods and functionality below.

func (dao tagStatusDao) Create(ctx context.Context, data entity.TagStatus) (int64, error) {
	result, err := model.GetDB().Ctx(ctx).Model(TagStatus.Table()).Data(data).Insert(data)
	if err != nil {
		return 0, err
	}
	id, err := result.LastInsertId()
	if err != nil {
		return 0, err
	}
	return id, nil
}
