// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframeP/frame/internal/dao/internal"
)

// trainsDao is the data access object for the table trains.
// You can define custom methods on it to extend its functionality as needed.
type trainsDao struct {
	*internal.TrainsDao
}

var (
	// Trains is a globally accessible object for table trains operations.
	Trains = trainsDao{internal.NewTrainsDao()}
)

// Add your custom methods and functionality below.
