// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframeP/frame/internal/dao/internal"
)

// trainSeatsDao is the data access object for the table train_seats.
// You can define custom methods on it to extend its functionality as needed.
type trainSeatsDao struct {
	*internal.TrainSeatsDao
}

var (
	// TrainSeats is a globally accessible object for table train_seats operations.
	TrainSeats = trainSeatsDao{internal.NewTrainSeatsDao()}
)

// Add your custom methods and functionality below.
