// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"
	"goframeP/frame/internal/dao/internal"
	"goframeP/frame/internal/model"
	"goframeP/frame/internal/model/entity"
)

// trainOrderDao is the data access object for the table train_order.
// You can define custom methods on it to extend its functionality as needed.
type trainOrderDao struct {
	*internal.TrainOrderDao
}

var (
	// TrainOrder is a globally accessible object for table train_order operations.
	TrainOrder = trainOrderDao{internal.NewTrainOrderDao()}
)

// Add your custom methods and functionality below.

func (dao trainOrderDao) Create(ctx context.Context, data entity.TrainOrder) (int64, error) {
	result, err := model.GetDB().Ctx(ctx).Model(TrainOrder.Table()).Data(data).Insert(data)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}
